version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    container_name: appPHP

  php-fpm:
    build: ./.docker/php-fpm
    volumes:
      - ./src:/var/www/html
    container_name: appPHPfpm

#    ./src:/var/www/html